<a href="https://colab.research.google.com/github/TechBison/ML-AI_CLASS/blob/master/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
def func_bug():
  try:
    m = 5/0 
  except Exception as es:
    print(es)


In [2]:
func_bug()

division by zero


In [5]:
subjects = ['Americans','Indian']
verbs = [' play',' watch']
objects = [' Baseball',' Cricket']

lis = [sub+ verb+ obj  for sub in subjects for verb in verbs for obj in objects]
for i in lis:
  print (i)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indian play Baseball
Indian play Cricket
Indian watch Baseball
Indian watch Cricket


In [0]:
import numpy as np 
def new_func(inpvec,n,increasing = False):
  if not increasing:
    mat = np.array([x**(n-1-i) for x in inpvec  for i in range(n)]).reshape(inpvec.size,n)
  else:
    mat = np.array([x**i for x in inpvec for i in range(n)]).reshape(inpvec.size,n)
  return mat

In [12]:
r = np.array([1,2,3,4])
op = new_func(r,4)
op2 = new_func(r,4,increasing=True)
print(op)
print (op2)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
